[package]
name = "openeq-render"
description = "Custom wgpu renderer (deferred G-buffer, shadow maps)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
openeq-assets = { path = "../openeq-assets" }
anyhow.workspace = true
tracing.workspace = true
wgpu.workspace = true
bytemuck.workspace = true
glam.workspace = true
pollster.workspace = true
image = { workspace = true, features = ["tga"] }
openeq-ui = { path = "../openeq-ui" }
fontdue = "0.9"
font8x8 = "0.3"

[[bin]]
name = "renderzone"
path = "src/bin/renderzone.rs"
