use super::*;

fn owner(position: [f32; 3], moved: bool, scale: f32) -> OwnerPose {
    let mut matrix = if moved {
        [
            [0., 0., 1., 0.],
            [1., 0., 0., 0.],
            [0., 1., 0., 0.],
            [0., 0., 0., 1.],
        ]
    } else {
        [
            [1., 0., 0., 0.],
            [0., 1., 0., 0.],
            [0., 0., 1., 0.],
            [0., 0., 0., 1.],
        ]
    };
    for row in &mut matrix[..3] {
        for v in &mut row[..3] {
            *v *= scale;
        }
    }
    matrix[3][..3].copy_from_slice(&position);
    OwnerPose::from_native_world(matrix).unwrap()
}

fn frame(dt: f32) -> FrameInput {
    FrameInput {
        delta_seconds: dt,
        owner: owner([10., 20., 30.], false, 1.),
        camera_position: [0.; 3],
        owner_suppressed: false,
        radial_motion_visible: true,
        draw_context: -1,
        owner_alpha: 1.,
    }
}

fn near(a: f32, b: f32) {
    assert!((a - b).abs() <= 2e-6 * b.abs().max(1.), "{a} != native {b}");
}

fn compare(particle: &Particle, native: [f32; 32]) {
    for i in 0..3 {
        near(particle.birth_origin[i], native[i]);
        for axis in 0..3 {
            near(particle.birth_axes[axis][i], native[3 + axis * 3 + i]);
        }
    }
    assert_eq!(particle.azimuth, native[12] as u16);
    for (actual, index) in [
        (particle.radial_distance, 13),
        (particle.axial_distance, 14),
        (particle.axial_speed, 17),
        (particle.radial_speed, 20),
        (particle.total_life, 23),
        (particle.remaining_life, 24),
    ] {
        near(actual, native[index]);
    }
}

/// Captured original x86 instructions, not expected values generated by this
/// implementation. Source/schema/hash are documented in WLD_PARTICLE_SAMPLER.md.
#[test]
fn original_instruction_snapshots_all_families_and_moving_culled_owners() {
    let data = include_bytes!("native_witness.bin");
    assert_eq!(&data[..4], b"WLP1");
    let mut cursor = 4;
    let word = |cursor: &mut usize| {
        let value = u32::from_le_bytes(data[*cursor..*cursor + 4].try_into().unwrap());
        *cursor += 4;
        value
    };
    let mut random = DiagnosticRandom::seed_one();
    for _ in 0..word(&mut cursor) {
        let definition = [
            PokDefinition::Smoke,
            PokDefinition::Flame301,
            PokDefinition::Flame308,
            PokDefinition::Flame500,
        ][word(&mut cursor) as usize];
        let case = word(&mut cursor);
        let mut sampler = Sampler::new(definition, -1);
        for step in 0..word(&mut cursor) {
            let dt = f32::from_bits(word(&mut cursor));
            let remaining = f32::from_bits(word(&mut cursor));
            let spawned = word(&mut cursor);
            let count = word(&mut cursor) as usize;
            let triangles = word(&mut cursor);
            let vertices: [u32; 32] = std::array::from_fn(|_| word(&mut cursor));
            let mut input = frame(dt);
            if case == 2 {
                input.owner = owner([10., 20., -30.], false, 1.);
                input.radial_motion_visible = false;
            }
            if case == 3 && step >= 2 {
                input.owner = owner([11., 22., 33.], true, 1.);
            }
            let samples = sampler.update(input, &mut random, |_| true).unwrap();
            if case == 0 {
                assert_eq!(sampler.spawn_counter(), spawned);
                assert_eq!(sampler.remaining_duration(), remaining);
            }
            assert_eq!(
                sampler.particles().len(),
                count,
                "case {case}, step {step}, {definition:?}"
            );
            for particle in sampler.particles() {
                compare(
                    particle,
                    std::array::from_fn(|_| f32::from_bits(word(&mut cursor))),
                );
            }
            // Early quads are all inside the controlled native viewport. Later
            // snapshot state checks do not substitute a guessed clipping rule.
            if case != 0 || step < 6 {
                assert_eq!(
                    samples.iter().filter(|p| p.draw).count() * 2,
                    triangles as usize
                );
            }
            if case == 0 && step < 6 {
                assert_eq!(samples[0].rgba[3], (vertices[4] >> 24) as u8);
                if step == 0 {
                    let width = f32::from_bits(vertices[8]) - f32::from_bits(vertices[0]);
                    // Subtracting two ~500-pixel f32 vertex coordinates loses
                    // more precision than comparing the original world size.
                    assert!((width - samples[0].size * 400. / 30.).abs() < 0.0002);
                }
            }
        }
    }
    assert_eq!(cursor, data.len());
}

#[test]
fn definition_admission_is_exact_and_does_not_follow_names_or_texture_aliases() {
    for definition in [
        PokDefinition::Smoke,
        PokDefinition::Flame301,
        PokDefinition::Flame308,
        PokDefinition::Flame500,
    ] {
        let mut cloud = ParticleCloud {
            fixed_words: *definition.fixed_words(),
            optional_vectors: None,
            optional_block: None,
            texture_reference: Some(openeq_assets::wld::Ref(470)),
            tail: vec![],
        };
        assert_eq!(PokDefinition::from_cloud(&cloud), Ok(definition));
        for i in 0..20 {
            cloud.fixed_words[i] ^= 1;
            assert_eq!(
                PokDefinition::from_cloud(&cloud),
                Err(SampleError::UnsupportedDefinition)
            );
            cloud.fixed_words[i] ^= 1;
        }
        cloud.tail.push(0);
        assert_eq!(
            PokDefinition::from_cloud(&cloud),
            Err(SampleError::UnsupportedDefinition)
        );
    }
}

#[test]
fn context_filters_drawing_without_pausing_life_or_radial_motion() {
    for captured in [-1, 0, 1] {
        for current in [-1, 0, 1] {
            let mut sampler = Sampler::new(PokDefinition::Flame301, captured);
            let mut random = DiagnosticRandom::seed_one();
            for dt in [0., 0.1] {
                let samples = sampler
                    .update(
                        FrameInput {
                            draw_context: current,
                            ..frame(dt)
                        },
                        &mut random,
                        |_| true,
                    )
                    .unwrap();
                assert_eq!(samples[0].draw, captured == current);
            }
            near(
                sampler.particles()[0].remaining_life,
                f32::from_bits(0x3f0ccccd),
            );
            assert!(sampler.particles()[0].radial_distance > 0.);
        }
    }
}

#[test]
fn delta_is_capped_and_invalid_input_is_atomic() {
    let mut a = Sampler::new(PokDefinition::Flame301, -1);
    let mut ra = DiagnosticRandom::seed_one();
    let mut b = a.clone();
    let mut rb = ra.clone();
    let sa = a.update(frame(90.), &mut ra, |_| true).unwrap();
    let sb = b.update(frame(1.), &mut rb, |_| true).unwrap();
    assert_eq!(sa, sb);
    assert_eq!(a.particles(), b.particles());
    for dt in [f32::NAN, f32::INFINITY, -0.1] {
        assert_eq!(
            a.update(frame(dt), &mut ra, |_| true),
            Err(SampleError::InvalidFrame)
        );
        assert_eq!(a.particles(), b.particles());
        assert_eq!(ra.counters(), rb.counters());
    }
    // Expiration occurs after this call's sampling and retires next call.
    assert_eq!(a.particles().len(), 1);
    assert!(a.particles()[0].remaining_life < 0.);
}

#[test]
fn native_distance_scale_alpha_suppression_context_and_expiry_controls() {
    let data = include_bytes!("native_controls.bin");
    assert_eq!(&data[..4], b"WLC1");
    let mut cursor = 4;
    let word = |cursor: &mut usize| {
        let value = u32::from_le_bytes(data[*cursor..*cursor + 4].try_into().unwrap());
        *cursor += 4;
        value
    };
    for _ in 0..word(&mut cursor) {
        let position = std::array::from_fn(|_| f32::from_bits(word(&mut cursor)));
        let scale = f32::from_bits(word(&mut cursor));
        let alpha = f32::from_bits(word(&mut cursor));
        let captured = word(&mut cursor) as i32;
        let context = word(&mut cursor) as i32;
        let mut sampler = Sampler::new(PokDefinition::Flame301, captured);
        let mut random = DiagnosticRandom::seed_one();
        for _ in 0..word(&mut cursor) {
            let dt = f32::from_bits(word(&mut cursor));
            let suppressed = word(&mut cursor) != 0;
            let radial_visible = word(&mut cursor) != 0;
            let remaining = f32::from_bits(word(&mut cursor));
            assert_eq!(word(&mut cursor), 0); // reserved
            let spawned = word(&mut cursor);
            let count = word(&mut cursor) as usize;
            let triangles = word(&mut cursor);
            let vertices: [u32; 32] = std::array::from_fn(|_| word(&mut cursor));
            let samples = sampler
                .update(
                    FrameInput {
                        delta_seconds: dt,
                        owner: owner(position, false, scale),
                        camera_position: [0.; 3],
                        owner_suppressed: suppressed,
                        radial_motion_visible: radial_visible,
                        draw_context: context,
                        owner_alpha: alpha,
                    },
                    &mut random,
                    |_| true,
                )
                .unwrap();
            assert_eq!(sampler.spawn_counter(), spawned);
            assert_eq!(sampler.remaining_duration(), remaining);
            assert_eq!(sampler.particles().len(), count);
            for particle in sampler.particles() {
                compare(
                    particle,
                    std::array::from_fn(|_| f32::from_bits(word(&mut cursor))),
                );
            }
            assert_eq!(
                samples.iter().filter(|p| p.draw).count() * 2,
                triangles as usize
            );
            if triangles > 0 {
                assert_eq!(samples[0].rgba[3], (vertices[4] >> 24) as u8);
                let rhw = f32::from_bits(vertices[3]);
                let width = f32::from_bits(vertices[8]) - f32::from_bits(vertices[0]);
                assert!((width - samples[0].size * 400. * rhw).abs() < 0.0002);
                // Invert native projected quad center to check world position.
                let x = (f32::from_bits(vertices[0]) + f32::from_bits(vertices[8])) * 0.5;
                let y = (f32::from_bits(vertices[1]) + f32::from_bits(vertices[17])) * 0.5;
                for (actual, native) in samples[0].position.into_iter().zip([
                    (x - 400.) / (400. * rhw),
                    (300. - y) / (400. * rhw),
                    1. / rhw,
                ]) {
                    near(actual, native);
                }
            }
        }
    }
    assert_eq!(cursor, data.len());
}

#[test]
fn original_torch_and_lamp_world_matrices_produce_native_birth_axes() {
    // Actual node world matrices and final particle bases from the frozen
    // placement witness, not the intermediate emitter bases. Source fragment
    // identities and witness hash are recorded in WLD_PARTICLE_SAMPLER.md.
    // Origin words preserve the exact native f32 output without decimal casts.
    for (definition, origin, world_rows, birth_axes) in [
        (
            PokDefinition::Flame301,
            [0x430c8e00, 0x44abe1c8, 0xc2c9af7a].map(f32::from_bits),
            [[1., 0., 0.], [0., 0., 1.], [0., -1., 0.]],
            [[0., 0., 1.], [1., 0., 0.], [0., -1., 0.]],
        ),
        (
            PokDefinition::Smoke,
            [0x430c8e00, 0x44abe1c8, 0xc2c8dd7a].map(f32::from_bits),
            [[1., 0., 0.], [0., 0., 1.], [0., -1., 0.]],
            [[0., 0., 1.], [1., 0., 0.], [0., -1., 0.]],
        ),
        (
            PokDefinition::Flame500,
            [0x446766ce, 0x43100260, 0xc2f8ed78].map(f32::from_bits),
            [[-1., 0., 0.], [0., 0., 1.], [0., 1., 0.]],
            [[0., 0., 1.], [-1., 0., 0.], [0., 1., 0.]],
        ),
    ] {
        let matrix = std::array::from_fn(|row| {
            std::array::from_fn(|col| match (row, col) {
                (3, 3) => 1.,
                (3, _) => origin[col],
                (_, 3) => 0.,
                _ => world_rows[row][col],
            })
        });
        let mut sampler = Sampler::new(definition, -1);
        let samples = sampler
            .update(
                FrameInput {
                    owner: OwnerPose::from_native_world(matrix).unwrap(),
                    ..frame(0.)
                },
                &mut DiagnosticRandom::seed_one(),
                |_| true,
            )
            .unwrap();
        assert_eq!(sampler.particles()[0].birth_origin, origin);
        assert_eq!(sampler.particles()[0].birth_axes, birth_axes);
        assert_eq!(samples[0].position, origin);
    }
}

#[test]
fn owner_matrix_rejects_unverified_shapes_and_degenerate_numbers() {
    let identity = [
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
    ];
    for (row, col, value) in [
        (0, 0, 0.),
        (0, 0, 2.),
        (1, 0, 0.2),
        (0, 3, 1.),
        (3, 3, 0.),
        (3, 0, f32::NAN),
    ] {
        let mut matrix = identity;
        matrix[row][col] = value;
        assert!(matches!(
            OwnerPose::from_native_world(matrix),
            Err(SampleError::UnsupportedOwnerTransform)
        ));
    }
    let mut tiny = identity;
    for (i, row) in tiny[..3].iter_mut().enumerate() {
        row[i] = f32::from_bits(1);
    }
    assert!(matches!(
        OwnerPose::from_native_world(tiny),
        Err(SampleError::UnsupportedOwnerTransform)
    ));
}
