use super::*;
use crate::texture::Texture;
use std::collections::BTreeSet;

fn rgba(word: u32) -> [u8; 4] {
    let [a, r, g, b] = word.to_be_bytes();
    [r, g, b, a]
}

fn sky() -> SkyAssets {
    SkyAssets {
        weather: "synthetic native witness palette".into(),
        color_map: Texture {
            name: "synthetic native witness palette".into(),
            width: 32,
            height: 32,
            rgba: (0..1024_u32)
                .flat_map(|i| rgba(0xa000_0000 | ((i * 0x010307) & 0xff_ffff)))
                .collect(),
        },
        color_map_layout: SkyColorMapLayout::OriginalDome,
        color_map_provenance: None,
        cloud_texture: None,
        cloud_color_map: None,
        cloud_color_map_layout: SkyColorMapLayout::FullTexture,
        cloud_color_map_provenance: None,
        cloud_velocity: 0.,
    }
}

fn crc32(bytes: impl Iterator<Item = u8>) -> u32 {
    let mut crc = flate2::Crc::new();
    crc.update(&bytes.collect::<Vec<_>>());
    crc.sum()
}

// CRCs and sparse XYZ bits below were extracted from original-instruction
// output in /tmp/openeq-sky-dome-geometry.json, SHA256
// cc9590d5bef8a8e1d774064c8c3593c287ec55f6da7e7793702536fb08b0a74c.
// They are fixed observations, not expected values generated by this port.
#[test]
fn all_indices_match_native_digest_and_keep_the_extra_cap_triangle() {
    let dome = NativeSkyDome::build(800., &sky()).unwrap();
    assert_eq!(std::mem::size_of::<NativeSkyVertex>(), 16);
    assert_eq!(dome.vertices.len(), 962);
    assert_eq!(dome.indices.len(), 5583);
    assert_eq!(dome.indices.len() / 3, 1861);
    assert_eq!(
        crc32(dome.indices.iter().flat_map(|i| i.to_le_bytes())),
        0x5eee_83b4
    );
    assert!(dome.indices.iter().all(|&i| usize::from(i) < 962));
    assert_eq!(&dome.indices[..9], &[0, 1, 2, 0, 2, 3, 0, 3, 4]);
    assert_eq!(
        &dome.indices[90..102],
        &[0, 31, 32, 33, 34, 1, 34, 2, 1, 34, 35, 2]
    );
    assert_eq!(&dome.indices[5580..], &[961, 929, 928]);
}

#[test]
fn all_source_addresses_match_native_digest_and_nonrectangular_domain() {
    let dome = NativeSkyDome::build(800., &sky()).unwrap();
    assert_eq!(dome.source_color_indices.len(), 962);
    assert_eq!(
        crc32(
            dome.source_color_indices
                .iter()
                .flat_map(|i| i.to_le_bytes())
        ),
        0x5492_5154
    );
    assert_eq!(&dome.source_color_indices[..5], &[0, 30, 29, 28, 27]);
    assert_eq!(&dome.source_color_indices[30..36], &[1, 0, 0, 32, 33, 34]);
    assert_eq!(&dome.source_color_indices[60..65], &[59, 60, 32, 33, 34]);
    assert_eq!(
        &dome.source_color_indices[957..],
        &[956, 928, 929, 930, 928]
    );
    let used = dome
        .source_color_indices
        .iter()
        .copied()
        .collect::<BTreeSet<_>>();
    assert_eq!(used.len(), 872);
    for index in 0..1024 {
        let row = index / 32;
        let column = index % 32;
        assert_eq!(
            used.contains(&index),
            row < 30 && column < if row == 0 { 31 } else { 29 }
        );
    }
}

#[test]
fn packed_diffuse_matches_native_witness_and_preserves_all_rgba_bits() {
    let mut sky = sky();
    let dome = NativeSkyDome::build(800., &sky).unwrap();
    assert_eq!(
        crc32(dome.vertices.iter().flat_map(|v| v.diffuse.to_le_bytes())),
        0x86a9_ee2e
    );
    // Independently vary every channel, especially alpha; no premultiplication,
    // gamma conversion or alpha normalization belongs in this CPU copy.
    let words = (0..1024_u32)
        .map(|i| i.wrapping_mul(0x9e37_79b9))
        .collect::<Vec<_>>();
    sky.color_map.rgba = words.iter().flat_map(|&word| rgba(word)).collect();
    let source_bytes = sky.color_map.rgba.clone();
    let colored = NativeSkyDome::build(800., &sky).unwrap();
    for (index, vertex) in colored.vertices.iter().enumerate() {
        assert_eq!(
            vertex.diffuse,
            words[colored.source_color_indices[index] as usize]
        );
        assert_eq!(vertex.position, dome.vertices[index].position);
    }
    assert_eq!(sky.color_map.rgba, source_bytes);
}

#[test]
fn native_sparse_positions_are_tolerance_bounded_without_regularizing_seams_or_caps() {
    let dome = NativeSkyDome::build(800., &sky()).unwrap();
    let witnesses = [
        (0, [0x00000000, 0x00000000, 0x44480000]),
        (1, [0x35ebbc2d, 0x40fffee8, 0x4447fd71]),
        (8, [0xc0fd0b2d, 0x3f9b0f44, 0x4447fd71]),
        (16, [0xbf4f3083, 0xc0feaeab, 0x4447fd71]),
        (31, [0x3fce2052, 0x40fac167, 0x4447fd71]),
        (32, [0x00000000, 0x40fffee8, 0x4447fd71]),
        (33, [0x37931768, 0x429fbbc5, 0x44470037]),
        (64, [0x00000000, 0x429fbbc5, 0x44470037]),
        (65, [0x38136457, 0x43200f50, 0x4443f4c5]),
        (129, [0x3890e5cb, 0x439d59e2, 0x4437e019]),
        (481, [0x3937ef2c, 0x4447be2a, 0x422239a2]),
        (496, [0xc2a1a94f, 0xc446b7d0, 0x422239a2]),
        (512, [0x00000000, 0x4447be2a, 0x422239a2]),
        (929, [0x38136455, 0x43200f4e, 0xc443f4c5]),
        (936, [0xc31e36ca, 0x41c1e673, 0xc443f4c5]),
        (960, [0x00000000, 0x43200f4e, 0xc443f4c5]),
        (961, [0x00000000, 0x00000000, 0xc4480000]),
    ];
    for (index, bits) in witnesses {
        for (axis, expected) in bits.map(f32::from_bits).into_iter().enumerate() {
            let actual = dome.vertices[index].position[axis];
            assert!(
                (actual - expected).abs() <= 0.000_062,
                "vertex {index}, axis {axis}: {actual} != {expected}"
            );
        }
    }
    assert_eq!(dome.radius, 800.);
    assert_eq!(dome.vertices[0].position, [0., 0., 800.]);
    assert_eq!(dome.vertices[961].position, [0., 0., -800.]);
    assert!(dome.vertices[1].position[2] + dome.vertices[929].position[2] > 16.);
    for ring in 0..30 {
        let first = dome.vertices[1 + ring * 32].position;
        let seam = dome.vertices[32 + ring * 32].position;
        assert!(first[0] > 0.);
        assert_eq!(seam[0], 0.);
        assert_ne!(first, seam);
    }
    let half = NativeSkyDome::build(400., &sky()).unwrap();
    for (a, b) in dome.vertices.iter().zip(&half.vertices) {
        assert_eq!(a.position.map(|v| v * 0.5), b.position);
    }
}

#[test]
fn native_winding_keeps_the_single_reversed_extra_triangle() {
    let dome = NativeSkyDome::build(800., &sky()).unwrap();
    let mut signs = Vec::new();
    for indices in dome.indices.chunks_exact(3) {
        let points = indices
            .iter()
            .map(|&i| dome.vertices[i as usize].position.map(f64::from))
            .collect::<Vec<_>>();
        let a = points[0];
        let b = points[1];
        let c = points[2];
        let ab: [f64; 3] = std::array::from_fn(|i| b[i] - a[i]);
        let ac: [f64; 3] = std::array::from_fn(|i| c[i] - a[i]);
        let normal = [
            ab[1] * ac[2] - ab[2] * ac[1],
            ab[2] * ac[0] - ab[0] * ac[2],
            ab[0] * ac[1] - ab[1] * ac[0],
        ];
        signs.push(
            (0..3)
                .map(|i| normal[i] * (a[i] + b[i] + c[i]) / 3.)
                .sum::<f64>(),
        );
    }
    assert!(signs[..1860].iter().all(|&v| v > 0.000_001));
    assert!(signs[1860] < -0.000_001);
}

#[test]
fn unused_source_words_are_ignored_but_near_pole_ring_colors_are_preserved() {
    let mut sky = sky();
    let dome = NativeSkyDome::build(800., &sky).unwrap();
    let used = dome
        .source_color_indices
        .iter()
        .copied()
        .collect::<BTreeSet<_>>();
    for (index, pixel) in sky.color_map.rgba.chunks_exact_mut(4).enumerate() {
        if !used.contains(&(index as u32)) {
            pixel.copy_from_slice(&[255, 0, 255, 255]);
        }
    }
    assert_eq!(
        NativeSkyDome::build(800., &sky).unwrap().vertices,
        dome.vertices
    );
    sky.color_map.rgba[30 * 4..31 * 4].copy_from_slice(&[1, 2, 3, 4]);
    sky.color_map.rgba[930 * 4..931 * 4].copy_from_slice(&[5, 6, 7, 8]);
    let changed = NativeSkyDome::build(800., &sky).unwrap();
    assert_eq!(changed.vertices[1].diffuse, 0x0401_0203);
    assert_eq!(changed.vertices[960].diffuse, 0x0805_0607);
    assert_eq!(changed.vertices[0].diffuse, dome.vertices[0].diffuse);
    assert_eq!(changed.vertices[961].diffuse, dome.vertices[961].diffuse);
}

#[test]
fn malformed_tables_and_invalid_radii_are_rejected() {
    let valid = sky();
    for radius in [0., -1., f32::NAN, f32::INFINITY, f32::NEG_INFINITY] {
        assert!(NativeSkyDome::build(radius, &valid).is_err());
    }
    let mut invalid = valid.clone();
    invalid.color_map_layout = SkyColorMapLayout::FullTexture;
    assert!(NativeSkyDome::build(800., &invalid).is_err());
    for (width, height, length) in [
        (31, 32, 4096),
        (32, 31, 4096),
        (32, 32, 4095),
        (32, 32, 4097),
    ] {
        let mut invalid = valid.clone();
        invalid.color_map.width = width;
        invalid.color_map.height = height;
        invalid.color_map.rgba.resize(length, 0);
        assert!(NativeSkyDome::build(800., &invalid).is_err());
    }
}
